name: Upload and Shorten URL

on: [push]

jobs:
  shorten-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Upload vbmeta.img and capture link
        id: upload
        run: |
          URL=$(curl --upload-file ./vbmeta.img https://transfer.sh/vbmeta.img)
          echo "::set-output name=url::$URL"
      
      - name: Shorten URL with is.gd
        run: |
          SHORT_URL=$(curl "https://is.gd/create.php?format=simple&url=${{ steps.upload.outputs.url }}&shorturl=patchedtwo")
          echo "Shortened URL: $SHORT_URL"
